/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Project_3_demo2;

import org.junit.Test;
import static org.junit.Assert.*;

public class mainTest {
    @Test public void testAppHasAGreeting() {

		// new object of lcs and calling the lcs calculator with sequence
		LCS lcs_object = new LCS();
		main main_object = new main();
		String[] sequences = main_object.sequenceGenerator();
		int mynum = lcs_object.lcsCalculator(sequences);
		int min = 0;

		assertTrue("LCS is out of range: " + mynum, min <= mynum);
    }
}
